[build]
  command = "npm run build"
  publish = "build/client"

[build.environment]
  NODE_VERSION = "19.9.0"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/[[path]]"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200